#  Q1: Basic NumPy Array

In [2]:
import numpy as np
from collections import Counter

## (a) Reverse the array

In [4]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 6 3 2 1]


## (b) Flatten a 2D array

In [6]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flat1 = array1.flatten()   
flat2 = array1.ravel()       
print(flat1)
print(flat2)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


## (c) Compare two arrays

In [8]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
comparison = np.array_equal(arr1, arr2)
print(comparison)

True


## (d) Most frequent value & indices

In [10]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
val_x = np.bincount(x).argmax()
indices_x = np.where(x == val_x)
print(val_x, indices_x)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
val_y = np.bincount(y).argmax()
indices_y = np.where(y == val_y)
print(val_y, indices_y)

1 (array([0, 5, 7, 8, 9], dtype=int64),)
1 (array([0, 1, 2], dtype=int64),)


## (e) For matrix: gfg

In [12]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum_all = np.sum(gfg)
row_sum = np.sum(gfg, axis=1)
col_sum = np.sum(gfg, axis=0)
print(sum_all)
print(row_sum)
print(col_sum)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


## (f) Matrix calculations

In [14]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

# i. Diagonal sum
diag_sum = np.trace(n_array)
print(diag_sum)

# ii. Eigenvalues
eig_vals = np.linalg.eigvals(n_array)
print(eig_vals)

# iii. Eigenvectors
eig_vals2, eig_vecs = np.linalg.eig(n_array)
print(eig_vecs)

# iv. Inverse
inv_matrix = np.linalg.inv(n_array)
print(inv_matrix)

# v. Determinant
det = np.linalg.det(n_array)
print(det)

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


## (g) Matrix multiplication & covariance

In [16]:
# i
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
product1 = np.dot(p1, q1)
cov1 = np.cov(p1.T, q1.T)
print(product1)
print(cov1)

# ii
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
product2 = np.dot(p2, q2)
cov2 = np.cov(p2.T, q2)
print(product2)
print(cov2)

[[16 19]
 [26 31]]
[[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]


## (h) Inner, outer, cartesian products

In [18]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner = np.inner(x, y)
outer = np.outer(x.flatten(), y.flatten())

cartesian = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)

print(inner)
print(outer)
print(cartesian)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


# Q2: NumPy Mathematics & Stats

## (a)

In [21]:
array = np.array([[1, -2, 3], [-4, 5, -6]])

# i. Absolute
abs_val = np.abs(array)

# ii. Percentiles
flat_percentile = np.percentile(array, [25, 50, 75])
row_percentile = np.percentile(array, [25, 50, 75], axis=1)
col_percentile = np.percentile(array, [25, 50, 75], axis=0)

# iii. Mean, Median, Std
mean_flat = np.mean(array)
median_flat = np.median(array)
std_flat = np.std(array)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

print(abs_val)
print(flat_percentile, row_percentile, col_percentile)
print(mean_flat, median_flat, std_flat)

[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5] [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]] [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
-0.5 -0.5 3.8622100754188224


## (b)

In [23]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floored = np.floor(a)
ceiled = np.ceil(a)
truncated = np.trunc(a)
rounded = np.round(a)

print(floored, ceiled, truncated, rounded)

[-2. -2. -1.  0.  1.  1.  3.] [-1. -1. -0.  1.  2.  2.  3.] [-1. -1. -0.  0.  1.  1.  3.] [-2. -2. -0.  0.  2.  2.  3.]


# Q3: Searching and Sorting

## (a)

In [26]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted
sorted_array = np.sort(array)

# ii. Indices
sorted_indices = np.argsort(array)

# iii. 4 smallest
smallest = np.sort(array)[:4]

# iv. 5 largest
largest = np.sort(array)[-5:]

print(sorted_array, sorted_indices, smallest, largest)

[ 10  16  16  52  54  62 453] [0 3 4 1 5 2 6] [10 16 16 52] [ 16  52  54  62 453]


## (b)

In [28]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# Integer elements
int_elements = array[np.floor(array) == array]

# Float elements
float_elements = array[np.floor(array) != array]

print(int_elements, float_elements)

[1. 2. 3. 2.] [1.2 2.2]


# Q4: Image to Array and Save as Text

## (a) Convert image to array and save

In [31]:
from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)

    if len(arr.shape) == 2:
        # Grayscale
        np.savetxt("gray_image.txt", arr, fmt='%d')
        print("Saved as gray_image.txt")
    else:
        # RGB
        reshaped = arr.reshape(-1, arr.shape[2])
        np.savetxt("rgb_image.txt", reshaped, fmt='%d')
        print("Saved as rgb_image.txt")

img_to_array("5.jpg")
img_to_array("sample_gray.png")

Saved as rgb_image.txt
Saved as gray_image.txt


## (b) Load the saved file

In [33]:
# For grayscale
gray_arr = np.loadtxt("gray_image.txt", dtype=int)

# For RGB (reshape if needed)
rgb_arr = np.loadtxt("rgb_image.txt", dtype=int)